# Generated by Django 6.0.2 on 2026-03-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_art_url',
            field=models.URLField(blank=True),
        ),
    ]
