# Generated by Django 6.0.2 on 2026-03-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicplayer", "0002_playlist_cover_art_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="is_collaborative",
            field=models.BooleanField(default=False),
        ),
    ]
